apiVersion: oda.tmforum.org/v1beta1
kind: component
metadata:
  name: TMFC028-partymanagement
  labels:
    oda.tmforum.org/componentName: TMFC028-partymanagement
    oda.tmforum.org/funtionalBlockName: PartyManagement
spec:
  type: TMFC028-partymanagement
  version: 1.1.0
  description: >-
    Party management ODA-Component specification, from Open-API reference
    implementation.
  maintainers:
    - name: Matteo Destino
      email: matteo.destino@accenture.com
      owners: null
    - name: Matteo Destino
      email: matteo.destino@accenture.com
coreFunction:
  exposedAPIs:
    - name: PartnershipTypeManagement
      id: TMF668
      isRequired: 'no'
      version: 4
      specification: >-
        https://raw.githubusercontent.com/tmforum-apis/TMF668_PartnershipTypeManagement/master/TMF668-PartnershipTypeManagement-v4.0.0.swagger.json
      implementation: '/{{.Release.Name}}-partnermngtapi'
      apitype: openapi
      path: >-
        /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/PartnershipTypeManagement/v4
      developerUI: >-
        /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/PartnershipTypeManagement/v4/docs
      port: 8080
      resources:
        - partnershipSpecification:
            - GET
            - GET/id
            - POST
            - PATCH/id
            - DELETE/id
    - name: PartyManagement
      id: TMF632
      isRequired: 'yes'
      version: 4
      specification: >-
        https://raw.githubusercontent.com/tmforum-apis/TMF632_PartyManagement/master/TMF632-PartyManagement-v4.0.0.swagger.json
      implementation: '/{{.Release.Name}}-partymngtapi'
      apitype: openapi
      path: '/{{.Release.Name}}-{{.Values.component.type}}/tmf-api/PartyManagement/v4'
      developerUI: >-
        /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/PartyManagement/v4/docs
      port: 8080
      resources:
        - individual:
            - GET
            - GET/id
            - POST
            - PATCH/id
            - DELETE/id
        - organization:
            - GET
            - GET/id
            - POST
            - PATCH/id
            - DELETE/id
    - name: Customer
      id: TMF629
      isRequired: 'no'
      version: 4
      specification: >-
        https://raw.githubusercontent.com/tmforum-apis/TMF629_CustomerManagement/master/TMF629-CustomerManagement-v4.0.0.swagger.json
      implementation: '/{{.Release.Name}}-custmngtapi'
      apitype: openapi
      path: >-
        /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/CustomerManagement/v4
      developerUI: >-
        /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/CustomerManagement/v4/docs
      port: 8080
      resources:
        - customer:
            - GET
            - GET/id
            - POST
            - PATCH/id
            - DELETE/id
    - name: ProcessFlowManagement
      id: TMF701
      isRequired: 'no'
      version: 4
      specification: >-
        https://raw.githubusercontent.com/tmforum-apis/TMF701_ProcessFlowManagement/master/TMF701-ProcessFlowManagement-v4.0.0.swagger.json
      implementation: '/{{.Release.Name}}-procmngttapi'
      apitype: openapi
      path: >-
        /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/ProcessFlowManagement/v4
      developerUI: >-
        /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/ProcessFlowManagement/v4/docs
      port: 8080
      resources:
        - processFlow:
            - GET
            - GET/id
            - POST
            - DELETE/id
        - taskFlow:
            - GET
            - GET/id
            - PATCH/id
    - name: Event
      id: TMF688
      isRequired: not
      version: 4
      specification: >-
        https://raw.githubusercontent.com/tmforum-apis/TMF671_Promotion/master/TMF671-Promotion-v4.0.0.swagger.json
      implementation: '/{{.Release.Name}}-PromotionManagement'
      apitype: openapi
      path: >-
        /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/PromotionManagement/v4
      developerUI: >-
        /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/PromotionManagement/v4/docs
      port: 8080
      resources:
        - event:
            - GET
            - GET /id
  dependantAPIs:
    - name: UserRolesandPermissions
      id: TMF672
      isRequired: 'yes'
      version: 4
      specification: >-
        https://raw.githubusercontent.com/tmforum-apis/TMF672_UserRolesandPermissions/master/TMF672-UserRolesandPermissions-v4.0.0.swagger.json
      apitype: openapi
      resources:
        - permission:
            - GET
            - GET/id
        - role:
            - GET
            - GET/id
    - name: PartyRoleManagement
      id: TMF669
      isRequired: 'no'
      version: 4
      specification: >-
        https://github.com/tmforum-apis/TMF669-PartyRoleManagement/blob/master/TMF669-PartyRoleManagement-v4.0.0.swagger.json
      apitype: openapi
      resources:
        - partyRole:
            - GET
            - GET /id
    - name: GeographicAddressManagement
      id: TMF673
      isRequired: 'no'
      version: 4
      specification: >-
        https://github.com/tmforum-apis/TMF673-GeographicAddressManagement/blob/master/TMF673-GeographicAddressManagement-v4.0.0.swagger.json
      apitype: openapi
      resources:
        - GeographicAddress:
            - GET
            - GET /id
        - name: GeographicSiteManagement
          id: TMF674
          isRequired: 'no'
          version: 4
          specification: >-
            https://github.com/tmforum-apis/TMF674-GeographicSiteManagement/blob/master/TMF674-GeographicSiteManagement-v4.0.0.swagger.json
          apitype: openapi
          resources: null
        - GeographicSite:
            - GET
            - GET /id
        - name: GeographicLocationManagement
          id: TMF675
          isRequired: 'no'
          version: 4
          specification: >-
            https://github.com/tmforum-apis/TMF675-GeographicLocationManagement/blob/master/TMF675-GeographicLocationManagement-v4.0.0.swagger.json
          apitype: openapi
          resources: null
        - GeographicSite:
            - GET
            - GET /id
    - name: ProcessFlowManagement
      id: TMF701
      isRequired: 'no'
      version: 4
      specification: >-
        ttps://raw.githubusercontent.com/tmforum-apis/TMF701_ProcessFlow/master/TMF701-ProcessFlow-v4.0.0.swagger.json
      apitype: openapi
      resources:
        - processFlow:
            - POST
            - GET
            - GET /id
            - DELETE
        - taskFlow:
            - PATCH
            - GET
            - GET /id
    - name: Event
      id: TMF688
      isRequired: 'no'
      version: 4
      specification: >-
        https://github.com/tmforum-apis/TMF688-Event/blob/master/TMF688-Event-v4.0.0.swagger.json
      apitype: openapi
      resources:
        - event:
            - GET
            - GET /id
  publishedEvents:
    - name: PartnershipTypeMaagement
      specification: >-
        https://raw.githubusercontent.com/tmforum-apis/TMF668_PartnershipTypeManagement/master/TMF668-PartnershipTypeManagement-v4.0.0.swagger.json
      implementation: '/{{.Release.Name}}-partnermngtapi'
      apitype: openapi
      port: 80
    - resources:
        PartnershipSpecification:
          - PartnershipSpecificationCreateEvent
          - PartnershipSpecificationChangeEvent
          - PartnershipSpecificationDeleteEvent
        Partnership:
          - PartnershipCreateEvent
          - PartnershipChangeEvent
          - PartnershipDeleteEvent
    - name: partyManagement
      specification: >-
        https://raw.githubusercontent.com/tmforum-apis/TMF632_PartyManagement/master/TMF632-PartyManagement-v4.0.0.swagger.json
      implementation: '/{{.Release.Name}}-partymngtapi'
      apitype: openapi
      port: 80
    - resources:
        Individual:
          - IndividualCreateEvent
          - IndividualAttributeValueChangeEvent
          - IndividualStateChangeEvent
          - IndividualDeleteEvent
        Organization:
          - OrganizationCreateEvent
          - OrganizationAttributeValueChangeEvent
          - OrganizationStateChangeEvent
          - OrganizationDeleteEvent
    - name: CustomerManagement
      specification: >-
        https://raw.githubusercontent.com/tmforum-apis/TMF629_CustomerManagement/master/TMF629-CustomerManagement-v4.0.0.swagger.json
      implementation: '/{{.Release.Name}}-custmngtapi'
      apitype: openapi
      port: 80
    - resources:
        customer:
          - CustomerCreateEvent
          - CustomerAttributeValueChangeEvent
          - CustomerStateChangeEvent
          - CustomerDeleteEvent
  subscribedEvents:
    - name: UserRolesandPermissions
      specification: >-
        https://raw.githubusercontent.com/tmforum-apis/TMF672_UserRolesandPermissions/master/TMF672-UserRolesandPermissions-v4.0.0.swagger.json
      apitype: openapi
      port: 80
    - >-
      resources UserRoles - UserRoleCreationNotification -
      UserRoleChangeNotification
    - name: PartyRoleManagement
      specification: >-
        https://github.com/tmforum-apis/TMF669-PartyRoleManagement/blob/master/TMF669-PartyRoleManagement-v4.0.0.swagger.json
      apitype: openapi
      port: 80
    - resources:
        artyRole:
          - PartyRoleCreateEvent
          - PartyRoleAttributeValueChangeEvent
          - PartyRoleStateChangeEvent
          - PartyRoleDeleteEvent
management: []
reporting: []
security: []
